.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. deuscoin_qt test_deuscoin_qt
clean: FORCE
	$(MAKE) -C .. deuscoin_qt_clean test_deuscoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_deuscoin_qt_check
deuscoin-qt deuscoin-qt.exe: FORCE
	 $(MAKE) -C .. deuscoin_qt
